### ISSUE TITLE
Does not open terminal with the path

### ISSUE THREAD

**Issue by vnl** [onmyway133/FinderGo#10]
Am I missing something? 
Followed everything and have given permission in Finder and also is in the finder window. 

I remember having issues while setting up right click open in terminal option too. 
    System Preferences > Keyboard > Shortcuts > Services > Enable New Terminal at Folder & New Terminal Tab at Folder
Both don't work for me. Not quite sure if its related to FinderGo not working too?

System Version:	macOS 10.14 (18A389)

**Comment by onmyway133** [comment]
@vnl Hi, sorry for the delay, can you check this new release https://github.com/onmyway133/FinderGo/releases/tag/1.3.0 ?

**Comment by onmyway133** [comment]
@vnl Hi, if you use Mojave, you can check https://github.com/onmyway133/FinderGo/releases/tag/1.4.0

**Comment by vnl** [comment]
@onmyway133  Thank you for this update. It is fixed now and will close the issue. It was the Mojave update which might have caused the issue.
