### ISSUE TITLE
Finder Sync Extension Missed

### ISSUE THREAD

**Issue by taohex** [onmyway133/FinderGo#2]
Hi,
Thank you for your wonderful app. But I can't setup up Finder Sync Extension.
I ran `curl -fsSL https://raw.githubusercontent.com/onmyway133/FinderGo/master/install.sh | sh`
and checked that `*.scpt` are created in `~/Library/Application Scripts/com.fantageek.FinderGo.FinderSyncExtension`. I restarted my mac and ran `killall Finder` several times. But Finder Sync Extension did not appear on my Finder. What should I do?

**Comment by onmyway133** [comment]
@taohex Hi, thanks for checking this out. I 've updated README with details on how to install it as extension. Feel free to ask again if something is not clear enough

**Comment by onmyway133** [comment]
@taohex Hi, hope that solves your issue. Feel free to reopen it if you have any problem

**Comment by taohex** [comment]
Hi, thank you. OK now! But the order is not correct in `README`. Enable FinderGo  in `System Preferences` should be done before drag onto toolbar.

**Comment by onmyway133** [comment]
@taohex Hi, thanks. I will fix that

**Comment by onmyway133** [comment]
@taohex Fixed as you suggested. Many thanks 🚀
