### ISSUE TITLE
Possible to configure a unique default console app?

### ISSUE THREAD

**Issue by lukaspili** [onmyway133/FinderGo#3]
Hi Onmyway133,
Thanks for this useful tool!

It would be great if the user could configure what options shows when clicking on the button in the finder. Currently it always shows the 3 options (terminal, iterm, hyper), while in practice a user uses always the same console app. By setting a unique default console app, it saves 1 mouse click 😄 

The tool could use a simple configuration file to offer this customization. What do you think? 

Thanks.

**Comment by onmyway133** [comment]
@lukaspili Hi, thanks for checking this out. Actually `FinderGo` has supports 
- Finder Sync extension: which shows a dropbox with 3 options like you describe
- macOS app: you can `cmd+drag` it to the Finder toolbar, it opens `iTerm` by default now

I could definitely store configuration into `UserDefaults` and we can configure that via command line. Feel free to make a PR if you have any suggestions 😇

**Comment by lucasdelucca** [comment]
Hi, @onmyway133! 

Can I change the default `iTerm` to OSX native Terminal?

**Comment by onmyway133** [comment]
@lukaspili @luccaccine Hi, this is the same as https://github.com/onmyway133/FinderGo/issues/6. Sorry that it takes long time, can you check this new release https://github.com/onmyway133/FinderGo/releases/tag/1.2.0 ?
