### ISSUE TITLE
Binary Isn't Signed

### ISSUE THREAD

**Issue by FlorianWendelborn** [onmyway133/FinderGo#5]
"FinderGo.app" can't be opened because it is from an unidentified developer.

Yes, I'm aware there are workarounds, still — this should be fixed.

**Comment by onmyway133** [comment]
@dodekeract Hi, it is because I haven't pushed the app to the Mac App Store. In the mean time you can try `Right click -> Open` https://support.apple.com/kb/PH25088?locale=en_US
