### ISSUE TITLE
Set default terminal.app instead of iTerm

### ISSUE THREAD

**Issue by thormengkheang** [onmyway133/FinderGo#6]
How to set default terminal.app instead of iTerm?

**Comment by onmyway133** [comment]
@james1888 Hi, I don't support it for now, but it's in the plan

**Comment by thormengkheang** [comment]
@onmyway133 oh nice hopefully soon :)

**Comment by Alalalalaki** [comment]
@onmyway133 
Hopefully it will also be supported for setting hyper as default.
Thanks for your app anyway.

**Comment by onmyway133** [comment]
@james1888 @Alalalalaki Hi, sorry that it takes long time, can you check https://github.com/onmyway133/FinderGo/releases/tag/1.2.0 ?

**Comment by thormengkheang** [comment]
@onmyway133 on the release page there is no app just the source

**Comment by onmyway133** [comment]
@james1888 Hi, I uploaded the binary again, can you check?

**Comment by thormengkheang** [comment]
@onmyway133 yeah I see it now :)

**Comment by Alalalalaki** [comment]
@onmyway133 Thanks so much.
