### ISSUE TITLE
Changing FinderGo toolbar icon

### ISSUE THREAD

**Issue by Stanko** [onmyway133/FinderGo#7]
Hello, first I want to thank you for the great little app!

This is not a issue, but rather something can be added to the readme.

Icon can be changed by right clicking on the FinderGo app and selecting "Get Info".
Once info dialog is opened, it is enough to drag iTerm app to the icon in the top left on the dialog (rounded in light blue on the screenshot). App will pick iTerm's icon in both toolbar and finder (rounded in blue on the screenshot). This will work for any other app you drag to it. 

<img width="1027" alt="screenshot 2018-07-06 10 16 17" src="https://user-images.githubusercontent.com/776788/42367955-0b1df66a-8106-11e8-9007-65b6a3d3a5ca.png">

Hope this helps, cheers!

**Comment by Musk66** [comment]
@Stanko Hi,how can I change the menu list to a one menu,I don't need the menu list,I want to set a FinderGo item for terminal directly.

**Comment by Stanko** [comment]
Hey there, I don't really understand what are you trying to do?

**Comment by onmyway133** [comment]
@Stanko Hi, thanks for the the tips. I think this should be familiar with advanced macOS users. I will refer to this issue if needed

**Comment by onmyway133** [comment]
@Stanko Hi, I refer to your instruction in README. Thanks ❤️

**Comment by ghaschel** [comment]
> @Stanko Hi,how can I change the menu list to a one menu,I don't need the menu list,I want to set a FinderGo item for terminal directly.

I'd like that too. I wish there was an option to set one as default, and not always opening a list to choose from.

**Comment by onmyway133** [comment]
@Stanko Hi, FinderGo works as both app and Finder extension. For app, you can just cmd+drag FinderGo app into the Finder toolbar

**Comment by Stanko** [comment]
It wasn't me who asked that :) but thank you!

**Comment by muwednesday** [comment]
Hey @onmyway133 , thanks for your excellent work. Just one suggestion, could you please make Finder Sync Extension as a button instead of a menu, just like Forklift. Then we can use command to change default terminal. It's much easier to use, and more elegant than just dragging app to the finder toolbar~ 
![image](https://user-images.githubusercontent.com/34086410/59083805-6144ab00-892b-11e9-9470-9eb1a1728663.png)

**Comment by onmyway133** [comment]
@muwednesday Hi, Finder Go is both mac app and Finder Sync extension
- With extension, you have 3 options: Terminal, iTerm and Hyper
- With mac app, you can cmd+drag to Finder toolbar, then `defaults write com.onmyway133.FinderGo terminal Terminal` to change terminal

**Comment by thevarunjain** [comment]
> @Stanko Hi,how can I change the menu list to a one menu,I don't need the menu list,I want to set a FinderGo item for terminal directly.

For that remove the FinderGo from System Preference > Extensions. 
Then go to Finder and click on customize the toolbar 
![image](https://user-images.githubusercontent.com/42597460/67083610-4e02e100-f150-11e9-9098-46bc766ec53d.png)
Finally, drag the app here and it will work a single button for default terminal (iterm2 in my case)

![image](https://user-images.githubusercontent.com/42597460/67083751-93bfa980-f150-11e9-99fc-11e2a8a1800f.png)
