### ISSUE TITLE
1.2.0 - app opens 2 windows, Extension opens 0

### ISSUE THREAD

**Issue by luckman212** [onmyway133/FinderGo#8]
Not sure if I've installed it incorrectly but on my Mac (10.13.6) when I drag FinderGo.app to the toolbar and run it from there, it opens **two** windows in iTerm (seems like 1 for each of my defined Profiles). It should just open the default profile, no?

Also, I tried the Finder extension, downloaded the scripts and enabled it in System Preferences, and even restarted. The button shows up and the menu items are all present, but when I click on them nothing happens. No errors and no Terminal or iTerm windows appear.

`¯\_(ツ)_/¯`

**Comment by luckman212** [comment]
https://github.com/onmyway133/FinderGo/pull/9 should fix the 2nd issue above. But, 2 windows are opening still, now that happens with the .app as well as the extension methods.

**Comment by onmyway133** [comment]
@luckman212 Hi, thanks for reporting. As you can see in the script, Finder app uses open command, and it opens 1 terminal for me `/usr/bin/open -a iTerm`

Are you using `Use System Window Restoration Setting` https://iterm2.com/why_no_content.html ?

**Comment by luckman212** [comment]
When I type `open -a iTerm` from Terminal.app I get only 1 window. But, using FinderGo I get 2 windows, 1 for each profile. As for iTerm preferences, I am set the the correct way I think:

![image](https://user-images.githubusercontent.com/1992842/45623228-9a16ba00-ba54-11e8-814f-e69a12f3a4a1.png)

Thanks for looking

**Comment by luckman212** [comment]
This can be closed. The issue was with iTerm after all, and has been fixed in the latest versions.

**Comment by onmyway133** [comment]
@luckman212 Glad to hear that 🚀
